// src/App.tsx
import type { RegisteredEvent } from '@/events'
import { getHandle, lastHandleKey, setHandle } from '@/persistence'
import { useEffect, useRef, useState } from 'react'
import type { DragEvent } from 'react'

const abortError = (error: unknown) => error instanceof DOMException && error.name === 'AbortError'

export default function App() {
    const [history, setHistory] = useState<FileSystemHandle | null>(null)
    const [dragging, setDragging] = useState(false)
    const [opening, setOpening] = useState(false)
    const [error, setError] = useState('')
    const [unavailable, setUnavailable] = useState(false)
    const dragDepth = useRef(0)

    useEffect(() => {
        getHandle(lastHandleKey)
            .then(setHistory)
            .catch(() => setHistory(null))

        if (!window.isSecureContext) {
            setUnavailable(true)
            setError('需要通过 HTTPS 访问')
        } else if (!navigator.serviceWorker?.controller) {
            setUnavailable(true)
            setError('Service Worker 不可用')
        }

        const onMessage = ({ data }: MessageEvent<RegisteredEvent>) => {
            if (data.type !== 'REGISTERED') return
            if (data.error) {
                setOpening(false)
                setError(data.error)
            } else {
                window.location.reload()
            }
        }
        const onControllerChange = () => window.location.reload()

        navigator.serviceWorker?.addEventListener('message', onMessage)
        navigator.serviceWorker?.addEventListener('controllerchange', onControllerChange)

        return () => {
            navigator.serviceWorker?.removeEventListener('message', onMessage)
            navigator.serviceWorker?.removeEventListener('controllerchange', onControllerChange)
        }
    }, [])

    async function open(handle: FileSystemHandle) {
        setOpening(true)
        setError('')

        try {
            let permission = await handle.queryPermission({ mode: 'read' })
            if (permission === 'prompt')
                permission = await handle.requestPermission({ mode: 'read' })
            if (permission !== 'granted') throw new Error('没有文件读取权限')

            await setHandle(lastHandleKey, handle)
            navigator.serviceWorker.controller?.postMessage({ type: 'REGISTER', handle })
        } catch (error) {
            setOpening(false)
            if (!abortError(error)) setError(error instanceof Error ? error.message : String(error))
        }
    }

    async function pickDirectory() {
        try {
            await open(await window.showDirectoryPicker({ mode: 'read' }))
        } catch (error) {
            if (!abortError(error)) setError(error instanceof Error ? error.message : String(error))
        }
    }

    function enterDropZone(event: DragEvent) {
        event.preventDefault()
        if (++dragDepth.current === 1) setDragging(true)
    }

    function leaveDropZone(event: DragEvent) {
        event.preventDefault()
        dragDepth.current = Math.max(0, dragDepth.current - 1)
        if (dragDepth.current === 0) setDragging(false)
    }

    async function drop(event: DragEvent) {
        event.preventDefault()
        dragDepth.current = 0
        setDragging(false)
        const handle = await event.dataTransfer.items[0]?.getAsFileSystemHandle()
        if (handle) await open(handle)
    }

    const historyLabel = history
        ? `继续打开 ${history.kind === 'directory' ? '文件夹' : '文件'}「${history.name}」`
        : ''

    return (
        <main className="stage">
            <section
                className={`launcher${dragging ? ' is-dragging' : ''}`}
                onDragEnter={enterDropZone}
                onDragLeave={leaveDropZone}
                onDragOver={event => event.preventDefault()}
                onDrop={drop}
            >
                <div className="frame" aria-hidden="true">
                    <span />
                    <span />
                    <span />
                    <span />
                </div>

                <p className="eyebrow">LOCAL SLIDE RUNTIME</p>
                <h1>
                    Presenter<span>/srv</span>
                </h1>
                <p className="lede">把构建结果交给浏览器，直接开始演示。</p>

                <div className="actions">
                    <button
                        className="primary"
                        disabled={opening || unavailable}
                        onClick={pickDirectory}
                    >
                        {opening ? '正在打开…' : '选择文件夹'}
                    </button>
                    {history && (
                        <button
                            className="secondary"
                            disabled={opening || unavailable}
                            onClick={() => open(history)}
                        >
                            {historyLabel}
                        </button>
                    )}
                </div>

                {error && (
                    <p className="error" role="alert">
                        {error}
                    </p>
                )}

                <div className="drop-hint">
                    <span>或拖入 web-app 文件夹 / ZIP</span>
                    <span className="line" />
                </div>

                <details>
                    <summary>这是做什么的？</summary>
                    <p>
                        Presenter-srv 在 Chromium 浏览器中直接运行 Presenter 导出的 Slidev SPA。
                        文件只在本地读取，不会上传。
                    </p>
                </details>
            </section>
        </main>
    )
}

// src/App.vue
<template>
    <div
        ref="box"
        class="box mx-auto max-w-40em mt-5em"
        :class="{ dragover }"
        @dragenter="dragover++"
        @dragleave="dragover--"
        @dragover.prevent
        @drop.prevent="onDragAndDrop"
    >
        <el-card>
            <div class="content">
                <h1 class="title">Presenter-srv</h1>
                <div class="flex justify-center">
                    <el-button :disabled="hasError" @click="pickFile" size="large"
                        >选择一个文件夹</el-button
                    >
                    <el-button v-if="history" :disabled="hasError" @click="useLast" size="large">{{
                        historyHint
                    }}</el-button>
                </div>
                <details class="mt-2em text-center">
                    <summary>如何使用？</summary>
                    <div class="text-justify my-1em">
                        <p>
                            &emsp;&emsp;这是
                            <a href="https://github.com/Mufanc/Presenter">Presenter</a>
                            的配套项目，让你能够仅用一个搭载了 Chromium 的浏览器就能完成 Slidev SPA
                            的部署工作。你只需要点击上方按钮选择 Presenter 打包时生成的 web-app
                            文件夹，即可进入演示模式。
                        </p>
                    </div>
                </details>
            </div>
        </el-card>
    </div>
</template>

<script setup lang="ts">
import { computedAsync } from '@vueuse/core'
import { ElMessage } from 'element-plus'
import { computed, onMounted, ref } from 'vue'
import 'element-plus/theme-chalk/el-message.css'
import { EventTypes, WindowEvent } from '@/events'
import { getHandle, lastHandleKey, setHandle } from '@/persistence'

const box = ref<HTMLElement>()
const dragover = ref(0)

function postMessage(event: WindowEvent) {
    navigator.serviceWorker?.controller?.postMessage(event)
}

const history = computedAsync(async () => {
    const value = await getHandle(lastHandleKey)
    console.log('history:', value)
    return value
})

const historyHint = computed(() => {
    const isDirectory = history.value instanceof FileSystemDirectoryHandle
    return `使用上一次的${isDirectory ? '文件夹' : '文件'}（${history.value?.name}）`
})

async function pickFile() {
    try {
        const handle = await window.showDirectoryPicker()
        console.log('pick:', handle)
        await swRegisterHandle(handle)
    } catch (err) {
        if (err instanceof DOMException && err.name === 'AbortError') {
            console.log('user canceled.')
        } else {
            throw err
        }
    }
}

async function useLast() {
    const handle = history.value
    if (!handle) return
    await swRegisterHandle(handle)
}

async function onDragAndDrop(event: DragEvent) {
    dragover.value--
    const handle = await event.dataTransfer?.items[0].getAsFileSystemHandle()
    console.log('drag and drop:', handle)
    if (!handle) return
    await swRegisterHandle(handle)
}

async function swRegisterHandle(handle: FileSystemHandle) {
    while ((await handle.queryPermission()) === 'prompt') {
        await handle.requestPermission({ mode: 'read' })
    }

    if ((await handle.queryPermission()) === 'granted') {
        await setHandle(lastHandleKey, handle)
        postMessage({ type: EventTypes.REGISTER, handle })
    } else {
        console.error('permission denied.')
    }
}

const hasError = ref(false)

function checkEnv() {
    function logE(message: string) {
        hasError.value = true
        ElMessage({ type: 'error', duration: 5000, message })
    }

    // ensure HTTPS
    if (!window.isSecureContext) {
        logE('需要 HTTPS')
    }

    if (!navigator.serviceWorker.controller) {
        logE('Service Worker 不可用')
    }
}

onMounted(() => {
    checkEnv()

    navigator.serviceWorker.oncontrollerchange = () => {
        ElMessage({
            type: 'success',
            message: 'Service Worker 已更新',
            duration: 5000
        })
    }

    navigator.serviceWorker.onmessage = event => {
        let ev = event.data as WindowEvent
        switch (ev.type) {
            case EventTypes.REGISTERED:
                if (!ev.error) {
                    window.location.reload()
                }

                break
        }
    }
})
</script>

<style scoped lang="less">
:global(#app) {
    position: fixed;
    inset: 0;
    background-color: #f0f0f0;
}

.title {
    text-align: center;
}

.box {
    position: relative;

    @fg-color: #aaa;

    .content {
        transition: all 0.2s ease-in-out;
    }

    &::after {
        content: '打开文件';
        position: absolute;
        inset: 10px;

        display: flex;
        justify-content: center;
        align-items: center;

        font-size: 2em;
        font-weight: bold;
        letter-spacing: 0.1em;

        color: @fg-color;
        border: 5px dashed @fg-color;

        opacity: 0;
        z-index: -1;
        transition: opacity 0.2s ease-in-out;
    }

    &.dragover {
        .content {
            filter: blur(10px);
        }

        &::after {
            display: flex;
            z-index: 0;
            opacity: 1;
        }
    }
}
</style>
